### ISSUE TITLE
4.24 업데이트 이후 아이돌 목록 로드 불가

### ISSUE THREAD

**Issue by rpaper** [HyphenK/mltdkei_v3#7]
로드 버튼 클릭시 딱 한장만 로드되고 멈춤

E:\mltdkei_pypy_v423>cd /d E:\mltdkei_pypy_v423\

E:\mltdkei_pypy_v423>.\pypy37\pypy3.exe .\code\mltdkei_pypy_jp.py
103,SSR+,ようこそ私達の劇場へ！　天海春香,0,0,1
Exception in Tkinter callback
Traceback (most recent call last):
  File "E:\mltdkei_pypy_v423\pypy37\lib-python\3\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "E:\mltdkei_pypy_v423\code\IdolList.py", line 275, in <lambda>
    button_load = Button(uil_set_container, text="Load", width=7, command=lambda: print_gui(make_list()))
  File "E:\mltdkei_pypy_v423\code\IdolList.py", line 229, in print_gui
    print(data)
UnicodeEncodeError: 'cp949' codec can't encode character '\u6765' in position 20: illegal multibyte sequence

**Comment by HyphenK** [comment]
~~직접 코드 수정 가능하시면 IdolList.py 229번째 줄 print(data) 지우고 실행시켜 주시겠어요? 디버깅때 쓴 코드를 안 지우고 내보낸 게 에러를 낸 거 같습니다.~~

수정 완료했습니다. code_4241로 교체하시면 됩니다.
